---
title: Jayme Hoffman
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Jayme Hoffman's blog
baseurl: ''
url: ''
twitter_username: JaymeHoffman
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
